# NumPy Basics - Part 2
This notebook continues the overview of NumPy basics.
### Reshaping Arrays

NumPy arrays can be reshaped using the *reshape* method. The size of the initial array must match the size of the reshaped array. Where possible, NumPy creates the reshaped array as a view but this is not guaranteed.

In [4]:
import numpy as np
a = np.arange(0, 25).reshape((5, 5))
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


If an one-dimensional array is to be transformed into a two-dimensional row or column matrix, then either the *reshape* method or the *newaxis* keyword can be used within a slice operation.  

In [5]:
b = np.array(np.arange(25))
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [6]:
# turn 'b' into a two-dimensional row vector
c = b[np.newaxis, :]
print(c)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]]


In [8]:
print("Shapes for 'b' and 'c' are {}, {}, respectively.".format(b.shape, c.shape))

Shapes for 'b' and 'c' are (25,), (1, 25), respectively.


In [9]:
# turn b into a two-dimensional column vetor
d = b[:, np.newaxis]
print(d)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]


In [13]:
print("The shape of 'd' is {}".format(d.shape))

The shape of 'd' is (25, 1)


In [14]:
# the row and column vecs could equivalently be created as follows
c_new = b.reshape((1, 25))
d_new = b.reshape((25, 1))

In [15]:
print("The shapes of 'c_new' and 'd_new' are {}, {}, respectively.".format(c_new.shape, d_new.shape))

The shapes of 'c_new' and 'd_new' are (1, 25), (25, 1), respectively.


### Concatenating Arrays

NumPy methods *np.concatenate*, *np.vstack* and *np.hstack* can be used to concatenate arrays.

*np.concatenate* accepts a tuple or list of two or more arrays as its first argument and creates a new array.

In [17]:
a = np.arange(10)
b = np.arange(10, 20)
c = np.arange(20, 30)

In [18]:
print(a, ",", b, ", ", c)

[0 1 2 3 4 5 6 7 8 9] , [10 11 12 13 14 15 16 17 18 19] ,  [20 21 22 23 24 25 26 27 28 29]


In [19]:
p = np.concatenate([a, b, c])
print(p)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]


In [20]:
# concatenate works with multi-dimensional arrays, too
d = np.arange(12).reshape((3, 4))
q = np.concatenate([d, d, d])
print(q)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [21]:
# use second axis as the concatenation direction
r = np.concatenate([d, d], axis=1)
print(r)

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]


When arrays have different dimensions, using *np.vstack* and *np.hstack* could be more intuitive.

In [22]:
# vertical stack
v1 = np.array([4, 5, 6])
v2 = np.arange(9).reshape(3, 3)
np.vstack([v1, v2])

array([[4, 5, 6],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
# horizontal stack
h1 = np.arange(5)[:, np.newaxis]
h2 = np.arange(25, 50).reshape(5, 5)
np.hstack([h1, h2])

array([[ 0, 25, 26, 27, 28, 29],
       [ 1, 30, 31, 32, 33, 34],
       [ 2, 35, 36, 37, 38, 39],
       [ 3, 40, 41, 42, 43, 44],
       [ 4, 45, 46, 47, 48, 49]])

*np.dstasck* stacks arrays along the third axis.

In [24]:
# dstack
x = np.arange(9).reshape((3, 3))
y = np.arange(9, 18).reshape((3, 3))
z = np.arange(18, 27).reshape((3, 3))

In [25]:
np.dstack([x, y, z])

array([[[ 0,  9, 18],
        [ 1, 10, 19],
        [ 2, 11, 20]],

       [[ 3, 12, 21],
        [ 4, 13, 22],
        [ 5, 14, 23]],

       [[ 6, 15, 24],
        [ 7, 16, 25],
        [ 8, 17, 26]]])

### Splitting Arrays
Functions *np.split*, *np.vsplit* and *np.hsplit* provide means of splitting arrays along split points passed as a list of indices. 

If the passed list of indices is *[n_0, n_1]*, then there will be 3 split arrays, with the first one consisting of elements up to but not including the index *n_0*, the second one consisting of elements from *n_0* to *n_1* but not including the latter index, and the third one consisting of the remaining elements starting at index *n_1*. 

If *n* number of indices are passed as split points, there will be *n + 1* sub-arrays.

In [26]:
s = np.arange(10)
s1, s2, s3 = np.split(s, [2, 7])
print(s1, s2, s3)

[0 1] [2 3 4 5 6] [7 8 9]


In [27]:
# np.vsplit
v = np.arange(12).reshape(4, 3)
print(v)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [28]:
upper, lower = np.vsplit(v, [2])
print(upper, "\n\n", lower)

[[0 1 2]
 [3 4 5]] 

 [[ 6  7  8]
 [ 9 10 11]]


In [29]:
# np.hsplit
h = np.arange(40).reshape(4, 10)
print(h)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]


In [30]:
left, right = np.hsplit(h, [5])
print(left, "\n\n", right)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]] 

 [[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]]
