# Broadcasting

Broadcasting is another means of achieving vectorized operations in NumPy. It is nothing but a set of rules for applying universal functions on arrays of different sizes.

A simple example of broadcasting follows:

In [4]:
import numpy as np
rand = np.random.RandomState(50)
X = rand.randint(10, size=(2, 3))
print(X)

[[0 0 1]
 [4 6 5]]


In [46]:
# add 20 to all the elements
print(X+20)

[[20 20 21]
 [24 26 25]]


One helpful way of thinking about what just happpened is to imagine that NumPy converted the value 10 into an array and stretched it so that its shape matched that of X. However, this is just a mental model, and is not what actually happens.

"Stretching" can involve both arrays during broadcasting.

In [45]:
a = np.array(np.arange(1, 11))[:, np.newaxis]
print(a)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [44]:
b = np.array(np.arange(1, 11))[np.newaxis, :]
print(b)

[[ 1  2  3  4  5  6  7  8  9 10]]


In [43]:
print(a.shape, b.shape)

(10, 1) (1, 10)


In [42]:
print(a*b)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


Let's pretend to be [instrumentalists](https://en.wikipedia.org/wiki/Instrumentalism), and imagine what just happened. Array *a* has shape (10, 1) and array *b* has shape (1, 10). Both these arrays were "stretched" to make their dimensions with size 1 match the corresponding dimension of the other array until the array shapes became identical. Then, element-wise multiplications were performed through the multiplication *ufunc*.

## Broadcasting Rules
The following rules govern broadcasting in NumPy:

1. When two arrays have different number of dimensions, the one with fewer dimensions is padded with ones on the left side. For example, if array *x* has shape (3, 1) and array *y* has shape (3, ), then the shape of array *y* is padded on the left with one(s) so that it becomes (1, 3).

2. When the shape of two arrays do not match, the array with shape equal to 1 is stretched so that it matches the shape of the corresponding dimension of the other array. Both arrays may stretch their dimensions with shape equal to 1. In the case of the arrays *x* and *y*, both arrays "stretch" their dimensions with shape equal 1 so that their shapes end up being (3, 3).

3. When two arrays have dimensions of different sizes and neither size equals 1, then NumPy raises an error. This would be the case if the array *x* had shape (2, 3) and *y* had shape (3, 2)




In [61]:
x = rand.randint(100, size = (2, 3))
y = rand.randint(100, size = (3, 2))

In [63]:
print(x, "\n")
print(y)

[[71 51 28]
 [24 91 46]] 

[[62 13]
 [71 36]
 [ 0 58]]


In [64]:
print(x.shape, y.shape)

(2, 3) (3, 2)


In [57]:
print(x+y)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

One final note: Broadcasting even works for fancy indexing, which will be covered in one of the future notebooks. In the case of fancy indexing, broadcasting tries to make the shapes of two arrays identical and return pairs of indices.