# Getting Fancy With Indexing

So far, we have seen ways of accessing arrays using indices, slices and Boolean masks. Examples follow:

In [1]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# access 'a' through simple indexing
print(a[-1])

9


In [3]:
# access 'a' through slicing
print(a[2:7])

[2 3 4 5 6]


In [4]:
# access 'a' through boolean mask to print even numbers > 0
even = (a % 2 == 0) & (a>0)
a[even]

array([2, 4, 6, 8])

### Fancy Indexing
Fancy indexing provides one more method for accessing and changing arrays. It is just like simple indexing but instead of scalars, arrays of indices are used.

In [5]:
# simple indexing
print(a[0], a[5], a[7])

0 5 7


In [6]:
# using fancy indexing
print(a[[0, 5, 7]])

[0 5 7]


Fancy indexing works with multi-dimensional arrays, too.

In [7]:
b = np.array(np.arange(12)).reshape((3, 4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Let's print the values in the intersections of the 1st, 2nd and 3rd row and the 4th, 2nd and 3rd column.

In [8]:
row = np.array([0, 1, 2])
col = np.array([3, 1, 2])
b[row, col]

array([ 3,  5, 10])

The indices used were the pairs [0, 3], [1, 1] and [2, 2].

It may be noticed that the shape of the indices determines the shape of the resultant array. 

Rules of broadcasting hold in the pairing of indices in fancy indexing. Let's print the 4th, 2nd and 3rd columns of rows 1 to 3. 

In [9]:
b[row[:, np.newaxis], col]

array([[ 3,  1,  2],
       [ 7,  5,  6],
       [11,  9, 10]])

Again, the resultant array reflects the shape of the broadcasted indices rather than the indexed array.

### Getting Even More Fancier
Fancy indexing can be used in conjunction with simple indexing, slicing and boolean masking.

In [10]:
# print array 'b'
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Print the first and last columns of the second row using simple indexing and fancy indexing:

In [11]:
b[1, [0, -1]]

array([4, 7])

Print columns 2nd through to last of the 1st and 3rd row using slicing and fancy indexing

In [12]:
b[[0, -1], 1:]

array([[ 1,  2,  3],
       [ 9, 10, 11]])

Print the first and last column of 3rd, 1st and 2nd row using fancy indexing and masking.

In [13]:
rows = np.array([2, 0, 1])
bool_mask = np.array([1, 0, 0, 1], dtype=bool)
bool_mask

array([ True, False, False,  True], dtype=bool)

In [14]:
b[rows[:, np.newaxis], bool_mask]

array([[ 8, 11],
       [ 0,  3],
       [ 4,  7]])